AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: A simple hello world Java 8 function
Resources:
  GetAllBooks:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: java8
      Handler: example.GetAllBooks
      CodeUri: ./build/libs/aws-sam-local-rest-api-1.0-SNAPSHOT.jar
      Events:
        GetAllBooks:
          Type: Api
          Properties:
            Path: /books
            Method: get