AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: A simple hello world Java 8 function
Resources:
  HelloWorld:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: java8
      Handler: example.HelloWorld
      CodeUri: ./target/aws-sam-example-java8-1.0-SNAPSHOT.jar